# Complete Pytorch Tensor Tutorial (Initializing Tensors, Math, Indexing, Reshaping)

A. Initializing Tensors.

B. Tensor Mathematical and Logical Operations.

C. Tensor Indexing.

D. Tensor Reshaping.

## A. Initializing Tensors:

### 1. Create a tensor with the following characteristics:
  1. A 2-D tensor of dimension (2x3) with values from 1 to 6, and print it and its shape.
  1. Its data type is float 32, and print it.
  1. Set the device to be CUDA (enables GPU) if available, otherwise set it to CPU, and print it.
  1. Set the requires-gradient to True, and print it.




In [22]:
import torch
print(torch.__version__)

device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32, device = device, requires_grad=True)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)
print(tensor.requires_grad)

1.11.0+cu113
tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
torch.float32
cpu
True


## Other Common Initialization Methods:
### 1. Create an empty tensor of size (3x3), and print it.

In [23]:
import torch 
print(torch.__version__)

tensor = torch.empty(size=(3,3))
print(tensor)

1.11.0+cu113
tensor([[6.4891e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16]])


### 2. Create a tensor of zeros of size (3,3), and print it.

In [24]:
tensor = torch.zeros((3,3))
print(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### 3. Create a tensor of ones of size (3,3), and print it.

In [25]:
tensor = torch.ones((3,3))
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### 4. Create a tensor with values from a uniform distribution in the interval 0 and 1 with size (3x3), and print it. 

In [26]:
tensor = torch.rand((3,3))
print(tensor)

tensor([[0.5371, 0.0468, 0.6686],
        [0.0079, 0.6701, 0.2146],
        [0.8813, 0.1367, 0.2771]])


### 5. Create a tensor that is an identity matrix of size (5x5), and print it.

In [27]:
tensor = torch.eye(5)
print(tensor)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


### 6. Create a tensor that is a range from 0 to 5 ([0, 5[) with step 1, and print it.

In [28]:
tensor = torch.arange(start=0, end=5, step=1)
print(tensor)

tensor([0, 1, 2, 3, 4])


### 7. Create a tensor that is a line space from 0.1 to 1 ([0.1, 1]) with 10 steps, and print it.

In [29]:
tensor = torch.linspace(start=0.1, end=1, steps=10)
print(tensor)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


### 8. Create a tensor with 5 values from normal distribution of mean=0 and std=1, and print it.

In [30]:
tensor = torch.empty((1,5)).normal_(mean=0, std=1)
print(tensor)

tensor([[0.5675, 1.1963, 1.4278, 1.8229, 0.6604]])


### 9. Create a tensor with 5 values from uniform distribution in the interval 5 to 10, and print it.

In [31]:
tensor = torch.empty(size=(1,5)).uniform_(5,10)
print(tensor)

tensor([[6.0392, 9.0459, 7.1632, 6.5617, 6.7008]])


### 10. Create a tensor that is a diagonal matric of size (3x3) with value of 1 (= identity matrix), and print it.

In [32]:
tensor = torch.diag(torch.ones(3))
print(tensor)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## How to Initialize and Convert Tensors to Other Data Types
### 1. Create a tensor that contains a range from 0 to 4 (included), print it, and its data type.
### 2. Convert its data type into boolean (0 = False, and non-zeros = True), print it, and its data type.
### 3. Convert its data type into int16 (short), print it, and its data type.
### 4. Convert its data type into int32 (int), print it, and its data type.
### 5. Convert its data type into int64 (long), print it, and its data type.
### 6. Convert its data type into float16 (half) (suitable to train NNs on newer GPUs 2000x with that data type), print it, and its data type.
### 7. Convert its data type into float32 (float), print it, and its data type.
### 8. Convert its data type into float64 (double), print it, and its data type.










In [59]:
import torch
print(torch.__version__)

tensor = torch.arange(5)
print(tensor.dtype)

boolean_tensor = tensor.bool()
print(boolean_tensor)
print(boolean_tensor.dtype)

short_tensor = tensor.short()
print(short_tensor)
print(short_tensor.dtype)

int_tensor = tensor.int()
print(int_tensor)
print(int_tensor.dtype)

long_tensor = tensor.long()
print(long_tensor)
print(long_tensor.dtype)

half_tensor = tensor.half()
print(half_tensor)
print(half_tensor.dtype)

float_tensor = tensor.float()
print(float_tensor)
print(float_tensor.dtype)

double_tensor = tensor.double()
print(double_tensor)
print(double_tensor.dtype)

1.11.0+cu113
torch.int64
tensor([False,  True,  True,  True,  True])
torch.bool
tensor([0, 1, 2, 3, 4], dtype=torch.int16)
torch.int16
tensor([0, 1, 2, 3, 4], dtype=torch.int32)
torch.int32
tensor([0, 1, 2, 3, 4])
torch.int64
tensor([0., 1., 2., 3., 4.], dtype=torch.float16)
torch.float16
tensor([0., 1., 2., 3., 4.])
torch.float32
tensor([0., 1., 2., 3., 4.], dtype=torch.float64)
torch.float64


## NumPy Array to Torch Tensor and Vice Versa:
### 1. Create a NumPy array of zeros of size (5,5).
### 2. Convert it into Torch Tensor. 
### 3. Convert it back to NumPy Array.

In [34]:
import numpy as np
import torch

numpy_array = np.zeros((5,5))
print(numpy_array)

tensor = torch.from_numpy(numpy_array)
print(tensor)

another_numpy_array = tensor.numpy()
print(another_numpy_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## B. Tensor Mathematical and Logical Operations:
### 1. Intialize 2 torch tensors with the the following values:
    1. [1, 2, 3]
    2. [9, 8, 7]
### 2. Declare an empty tensor of size (1,3).
### 3. Apply the addition using 4 methods and print the result for each one.

In [35]:
import torch
print(torch.__version__)

first_tensor = torch.tensor([1,2,3])
second_tensor = torch.tensor([9,8,7])
third_tensor = torch.empty(3)

third_tensor = torch.add(first_tensor, second_tensor)
print(third_tensor)

torch.add(first_tensor, second_tensor, out = third_tensor)
print(third_tensor)

third_tensor = torch.add(first_tensor, second_tensor)
print(third_tensor)

third_tensor = first_tensor + second_tensor
print(third_tensor)

1.11.0+cu113
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([10, 10, 10])


### 4. Subract the two tensors and print the result.

In [36]:
third_tensor = first_tensor - second_tensor
print(third_tensor)

tensor([-8, -6, -4])


### 5. Apply the element wise division and print the result.
### 6. Divide the first tensor with an integer and print the result.

In [37]:
third_tensor = torch.true_divide(first_tensor, second_tensor)
print(third_tensor)

third_tensor = torch.true_divide(first_tensor, 6)
print(third_tensor)

tensor([0.1111, 0.2500, 0.4286])
tensor([0.1667, 0.3333, 0.5000])


### 7. (Inplace Operations) Apply the inplace addition operation (done without creating a new copy of tensor - computationally efficient) using 2 methods and print the result for each one.

In [38]:
third_tensor.add_(first_tensor)
print(third_tensor)

third_tensor += first_tensor 
print(third_tensor)

# third_tensor = third_tensor + first_tensor ==> is not inplace operation.

tensor([1.1667, 2.3333, 3.5000])
tensor([2.1667, 4.3333, 6.5000])


### 8. (Exponentiation) Apply element-wise power of 2 for a tensor using 2 methods and print the result for each one.

In [39]:
third_tensor = first_tensor.pow(2)
print(third_tensor)

third_tensor = first_tensor ** 2
print(third_tensor)

tensor([1, 4, 9])
tensor([1, 4, 9])


### 9. (Element-wise Comparison) Show which elements of the first tensor is greater than 2 and print the result. 

In [40]:
result = first_tensor > 2
print(result)

print(first_tensor[result])
print(first_tensor[first_tensor > 2])

tensor([False, False,  True])
tensor([3])
tensor([3])


### 10. (Matrix Multiplication) Initialize 2 matrices of sizes (2,5) and (5,3) by Uniform Distribution, apply matrix multiplication using 2 methods, and print the result.

In [41]:
first_matrix = torch.rand((2,5))
second_matrix = torch.empty((5,3)).uniform_()

result = torch.mm(first_matrix, second_matrix)
print(result)

result = first_matrix.mm(second_matrix)
print(result)

tensor([[0.7006, 0.6137, 0.5971],
        [1.7048, 0.8872, 1.4974]])
tensor([[0.7006, 0.6137, 0.5971],
        [1.7048, 0.8872, 1.4974]])


### 11. Apply element-wise matrix multiplication.

In [42]:
first_matrix = torch.rand((2,5))
second_matrix = torch.empty((2,5)).uniform_()

result = first_matrix * second_matrix
print(result)

tensor([[0.0029, 0.3879, 0.0048, 0.5623, 0.6847],
        [0.0301, 0.1212, 0.1161, 0.0053, 0.2187]])


### 12. (Matrix Exponentiation is not element-wise exponent) Apply matrix exponentiation on the first matrix using 2 methods, and compare the result with the element-wise matrix exponent.

In [43]:
matrix = torch.randn((3,3))

result = matrix.matrix_power(3)
print(result)

result = torch.mm(torch.mm(matrix, matrix), matrix)
print(result)

result = torch.pow(matrix, 3)
print(result)

result = matrix ** 3
print(result)

tensor([[ 0.3111, -0.0661, -0.5046],
        [-0.4240, -0.0942,  0.0805],
        [-2.1852, -0.0132,  1.7426]])
tensor([[ 0.3111, -0.0661, -0.5046],
        [-0.4240, -0.0942,  0.0805],
        [-2.1852, -0.0132,  1.7426]])
tensor([[-4.4944e-03, -5.9043e-04, -5.2254e-02],
        [-1.0976e-01, -5.0221e-02,  1.2162e-06],
        [-4.3043e+00, -1.2852e-04,  7.4751e-01]])
tensor([[-4.4944e-03, -5.9043e-04, -5.2254e-02],
        [-1.0976e-01, -5.0221e-02,  1.2162e-06],
        [-4.3043e+00, -1.2852e-04,  7.4751e-01]])


### 13. Apply the dot product on 2 vectors.

In [44]:
first_vector = torch.rand(5)
second_vector = torch.randn(5)

result = torch.dot(first_vector, second_vector)
print(result)

tensor(0.5508)


### 14. (Batch Matrix Multiplication)
    1. Initialize first tensor of size (batch, n, m)
    2. Initialize second tensor of size (batch, m, p)
    3. Apply Batch Matrix Multiplication (the result size is (batch, n, p))

In [45]:
batch = 32
n = 10
m = 20
p = 30

first_tensor = torch.rand((batch, n, m))
second_tensor = torch.rand((batch, m, p))

out_bmm = torch.bmm(first_tensor, second_tensor)

print(out_bmm)
print(out_bmm.shape)

tensor([[[6.0393, 6.1747, 4.4017,  ..., 4.3173, 5.1638, 6.3142],
         [5.5537, 5.3114, 5.6284,  ..., 3.7283, 5.1007, 4.5339],
         [5.2713, 5.5891, 4.9159,  ..., 4.2176, 5.3852, 5.7832],
         ...,
         [4.9657, 4.4003, 4.4774,  ..., 3.2888, 4.8117, 4.2683],
         [6.6085, 6.0306, 5.0172,  ..., 4.3873, 5.4924, 6.6792],
         [6.1697, 5.9107, 5.6817,  ..., 3.6848, 5.5764, 6.3116]],

        [[4.4364, 4.6060, 4.1285,  ..., 3.5674, 4.5713, 4.2894],
         [4.0824, 4.9272, 4.2097,  ..., 3.7135, 4.0226, 4.8559],
         [5.8922, 6.6212, 5.9120,  ..., 4.5240, 5.0612, 6.5160],
         ...,
         [5.1569, 5.1184, 5.1444,  ..., 3.8668, 4.1567, 4.7845],
         [5.9981, 6.2390, 5.3153,  ..., 4.5803, 4.5659, 6.0041],
         [4.6406, 5.0348, 4.1402,  ..., 3.3312, 3.7400, 4.4932]],

        [[4.4244, 4.6908, 3.8469,  ..., 3.1338, 3.7348, 2.8723],
         [3.5232, 4.1884, 3.9640,  ..., 3.8781, 3.6669, 3.4451],
         [3.9584, 4.5768, 3.9833,  ..., 4.0239, 3.8080, 3.

### 15. (Broadcasting) 
    1. Initialize 2 tensors of shape (5,5) and (1,5) respectively by uniform distribution.
    2. Apply broadcasting subtraction and power.

In [46]:
first_tensor = torch.rand((5,5))
second_tensor = torch.empty((1,5)).uniform_()

subtraction_result = first_tensor - second_tensor
print(subtraction_result)
print(subtraction_result.shape)

power_result = first_tensor ** second_tensor
print(power_result)
print(power_result.shape)

tensor([[-0.7334, -0.7776,  0.3197,  0.9081, -0.7416],
        [ 0.0066, -0.8675,  0.2074,  0.3608, -0.0246],
        [ 0.0975, -0.8847, -0.1082,  0.2064, -0.4302],
        [-0.0257, -0.8198,  0.2292,  0.6637,  0.0470],
        [-0.2379,  0.0267,  0.5678,  0.6572, -0.6372]])
torch.Size([5, 5])
tensor([[0.0190, 0.1528, 0.8758, 0.9985, 0.1352],
        [0.8044, 0.0482, 0.8186, 0.9803, 0.8368],
        [0.8759, 0.0261, 0.6106, 0.9698, 0.4683],
        [0.7786, 0.1052, 0.8301, 0.9922, 0.8981],
        [0.5997, 0.9357, 0.9851, 0.9920, 0.2563]])
torch.Size([5, 5])


## Some Useful Tensor Operations

### 1. Apply a matrix summation on rows. 

In [2]:
import torch
print(torch.__version__)

matrix = torch.empty((5,5)).uniform_(-5,5)
print(matrix)

result = torch.sum(matrix, dim=0, keepdim=True)
print(result.shape)

1.9.0+cu102
tensor([[ 2.2884,  0.8904,  4.1746, -2.8339,  1.3797],
        [ 2.1219, -1.9467, -3.8858,  3.1048,  0.4241],
        [-0.9805,  0.3403,  2.1123, -1.5146, -4.0420],
        [ 3.9690,  3.4765, -3.3431,  3.5805, -3.9511],
        [ 2.1640, -2.6728,  1.8368,  0.1814,  1.8020]])
torch.Size([1, 5])


### 2. Apply a matrix summation on columns.

In [48]:
result = torch.sum(matrix, dim=1, keepdim=True)
print(result.shape)

torch.Size([5, 1])


### 3. Get the maximum elements and their indices of a matrix (rank 2 tensor) for each column.

In [49]:
max_numbers, max_indices = torch.max(matrix, dim=0, keepdim=True)
print(max_numbers)
print(max_indices)

tensor([[4.5234, 4.7529, 3.0732, 4.3411, 2.5643]])
tensor([[3, 4, 0, 0, 0]])


### 4. Get the minimum elements and their indices of a matrix (rank 2 tensor) for each row.

In [50]:
min_numbers, min_indices = torch.min(matrix, dim=1, keepdim=True)
print(min_numbers, min_indices)

tensor([[-0.7348],
        [-3.4211],
        [-2.1932],
        [-4.3729],
        [-4.3303]]) tensor([[0],
        [4],
        [4],
        [1],
        [2]])


### 5. Calculate the absolute values of a matrix (rank 2 tensor).

In [51]:
abs_values = torch.abs(matrix)
print(abs_values)

tensor([[0.7348, 3.3440, 3.0732, 4.3411, 2.5643],
        [0.6961, 2.0588, 2.0040, 4.0956, 3.4211],
        [3.9869, 4.6786, 0.5496, 2.3444, 2.1932],
        [4.5234, 4.3729, 3.2564, 3.9333, 1.3123],
        [0.9171, 4.7529, 4.3303, 3.7089, 3.3354]])


### 6. Get the indices of maximum elements only of a matrix (rank 2 tensor) for each column.

In [52]:
max_indices = torch.argmax(matrix, dim=0, keepdim=True)
print(max_indices, max_indices.shape)

max_values, max_indices = torch.max(matrix, dim=0, keepdim=True)
print(max_indices, max_indices.shape) 

tensor([[3, 4, 0, 0, 0]]) torch.Size([1, 5])
tensor([[3, 4, 0, 0, 0]]) torch.Size([1, 5])


### 7. Get the indices of minimum elements only of a matrix (rank 2 tensor) for each column.

In [53]:
min_indices = torch.argmin(matrix, dim=0, keepdim=True)
print(min_indices, min_indices.shape)

min_values, min_indices = torch.min(matrix, dim=0, keepdim=True)
print(min_indices, min_indices.shape)

tensor([[4, 3, 4, 3, 1]]) torch.Size([1, 5])
tensor([[4, 3, 4, 3, 1]]) torch.Size([1, 5])


### 8. Get the mean elements of a matrix (rank 2 tensor) for each column.
- The mean is calculated only for floating types.

In [54]:
mean_values = torch.mean(matrix, dim=0, keepdim=True)
print(mean_values, mean_values.shape)

tensor([[ 1.2325,  1.2688, -1.1936,  2.1113, -1.5396]]) torch.Size([1, 5])


### 9. Apply an element-wise compare (check the equality) of 2 vectors.

In [56]:
first_vector = torch.rand(5)
second_vector = torch.randn(5)

compare_result = torch.eq(first_vector, second_vector)
print(compare_result)

compare_all_elements = torch.all(compare_result)
print(compare_all_elements)

message = 'Equal' if compare_all_elements == True else 'Not Equal'
print(message)

tensor([False, False, False, False, False])
tensor(False)
Not Equal


### 10. Apply an element-wise compare (check the equality) of 2 matrices.

In [4]:
first_matrix = torch.rand((5,2))
second_matrix = torch.randn((5,2))

compare_result = torch.eq(first_matrix, second_matrix)
print(compare_result, compare_result.shape)

compare_all_elements = torch.all(compare_result)
print(compare_all_elements)

message = 'Equal' if compare_all_elements == True else 'Not Equal'
print(message)

tensor([[False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False]]) torch.Size([5, 2])
tensor(False)
Not Equal


### 11. Sort each column in a matrix ascendingly. Then, print the sorted matrix and the indices.

In [5]:
sorted_matrix_values, sorted_matrix_indices = torch.sort(first_matrix, dim=0, descending=False)

print(sorted_matrix_values)
print(sorted_matrix_values.shape)

print(sorted_matrix_indices)
print(sorted_matrix_indices.shape)

tensor([[0.0689, 0.0658],
        [0.2408, 0.0794],
        [0.4543, 0.2062],
        [0.5591, 0.5915],
        [0.8859, 0.7165]])
torch.Size([5, 2])
tensor([[3, 4],
        [4, 1],
        [0, 3],
        [2, 2],
        [1, 0]])
torch.Size([5, 2])


### 12. Clamp all negative values of a matrix to be zero and all values greater than 10 will be 10.

In [13]:
matrix = torch.empty((5,3)).normal_(0,15)
print(matrix)

clampped_matrix = torch.clamp(matrix, min=0, max=10)
print(clampped_matrix)

matrix[matrix < 0.0] = 0.0
matrix[matrix > 10.0] = 10.0
print(matrix)

tensor([[  6.6880,  -0.7806,  -3.6483],
        [ -3.8671,  -3.5930, -16.9277],
        [  5.9661,  -1.4540,  -6.7087],
        [ -0.1445,  16.2445, -20.9530],
        [ 15.3148,  -6.0732,  17.8940]])
tensor([[ 6.6880,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 5.9661,  0.0000,  0.0000],
        [ 0.0000, 10.0000,  0.0000],
        [10.0000,  0.0000, 10.0000]])
tensor([[ 6.6880,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 5.9661,  0.0000,  0.0000],
        [ 0.0000, 10.0000,  0.0000],
        [10.0000,  0.0000, 10.0000]])


### 13. Check any of the tensor values are True.
### 14. Check all tensor values are True.

In [14]:
bool_tensor = torch.tensor([-1, 0, 1, 90], dtype=bool)
print(bool_tensor)

any_true = torch.any(bool_tensor)
print(any_true)

all_true = torch.all(bool_tensor)
print(all_true)

tensor([ True, False,  True,  True])
tensor(True)
tensor(False)


## C. Tensor Indexing
### 1. Initialize a rank-2 tensor with 10 examples and 25 features using a uniform distribution.
### 2. Get all features of the 1st example.
### 3. Get the 5th features of all examples.

In [19]:
batch = torch.empty((10, 25)).uniform_()

first_example = batch[0,:]
print(first_example)
print(first_example.shape)

first_example = batch[0,:].reshape(1, -1)
print(first_example)
print(first_example.shape)

first_example = batch[0]
print(first_example)
print(first_example.shape)

first_example = batch[0].reshape(1, -1)
print(first_example)
print(first_example.shape)

fifth_feature = batch[:, 4]
print(fifth_feature)
print(fifth_feature.shape)

tensor([0.5110, 0.9286, 0.0184, 0.8330, 0.3077, 0.8575, 0.5121, 0.7162, 0.8949,
        0.4770, 0.7837, 0.4637, 0.4515, 0.6384, 0.9991, 0.1430, 0.3783, 0.9130,
        0.6653, 0.2400, 0.8435, 0.5740, 0.4346, 0.4226, 0.0400])
torch.Size([25])
tensor([[0.5110, 0.9286, 0.0184, 0.8330, 0.3077, 0.8575, 0.5121, 0.7162, 0.8949,
         0.4770, 0.7837, 0.4637, 0.4515, 0.6384, 0.9991, 0.1430, 0.3783, 0.9130,
         0.6653, 0.2400, 0.8435, 0.5740, 0.4346, 0.4226, 0.0400]])
torch.Size([1, 25])
tensor([0.5110, 0.9286, 0.0184, 0.8330, 0.3077, 0.8575, 0.5121, 0.7162, 0.8949,
        0.4770, 0.7837, 0.4637, 0.4515, 0.6384, 0.9991, 0.1430, 0.3783, 0.9130,
        0.6653, 0.2400, 0.8435, 0.5740, 0.4346, 0.4226, 0.0400])
torch.Size([25])
tensor([[0.5110, 0.9286, 0.0184, 0.8330, 0.3077, 0.8575, 0.5121, 0.7162, 0.8949,
         0.4770, 0.7837, 0.4637, 0.4515, 0.6384, 0.9991, 0.1430, 0.3783, 0.9130,
         0.6653, 0.2400, 0.8435, 0.5740, 0.4346, 0.4226, 0.0400]])
torch.Size([1, 25])
tensor([0.3077, 0.

### 4. Get the first 10 features of the 3rd example. 

In [20]:
third_example_10_features = batch[2,:10]
print(third_example_10_features)
print(third_example_10_features.shape)

tensor([0.4754, 0.7265, 0.6043, 0.6524, 0.9612, 0.6160, 0.3907, 0.8526, 0.8630,
        0.0070])
torch.Size([10])


### 5. Change the value of the first feature of the first example to 100. 

In [21]:
batch[0, 0] = 100

### 6. Initialize a tensor that has values from 0 to 9.
### 7. Using one statement, pick 3 values from it (3rd, 6th, 9th). 

In [22]:
tensor = torch.arange(10)
indices_list = [2, 5, 8]
selected_values = tensor[indices_list]
print(selected_values)
print(selected_values.shape)

tensor([2, 5, 8])
torch.Size([3])


### 8. Pick 2 values from a matrix using 2 tensor of indices

In [25]:
matrix = torch.rand((5,3))

rows = torch.tensor([1, 0])
columns = torch.tensor([0, 2])

result = matrix[rows, columns]

print(matrix)
print(result)
print(result.shape)

tensor([[0.0962, 0.4596, 0.5590],
        [0.7160, 0.4338, 0.1199],
        [0.0679, 0.8133, 0.1035],
        [0.0065, 0.9988, 0.0893],
        [0.4538, 0.9602, 0.4458]])
tensor([0.7160, 0.5590])
torch.Size([2])


### 9. Initialize a tensor that has values from 0 to 9.
### 10. Pick elements that are greater than 2 and less than 8.
### 11. Pick elements that are less that 2 or greater than 8.
### 12. Pick elements that are less that 2 and greater than 8.
### 13. Pick elements that are even.

In [39]:
tensor = torch.arange(10)

result = tensor[(tensor>2) & (tensor<8)]
print(result)

result = tensor[(tensor<2) | (tensor>8)]
print(result)

result = tensor[(tensor<2) & (tensor>8)]
print(result)

result = tensor[tensor%2 == 0]
print(result)

result = tensor[torch.remainder(tensor,2) == 0]
print(result)

tensor([3, 4, 5, 6, 7])
tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])
tensor([0, 2, 4, 6, 8])


### 14. Double the values of a tensor if they are not greater than 5.

In [44]:
tensor = torch.arange(10)
print(tensor)

result = torch.where(tensor > 5, tensor, tensor*2)
print(result)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


### 15. Initailze a tensor with the following values [1, 0, 0, 12, 12, 1, -1, 7, -1], and print the unique values of it.

In [45]:
tensor = torch.tensor([1,0,0,12,12,1,-1,7,-1])
unique_values = tensor.unique()
print(unique_values)

tensor([-1,  0,  1,  7, 12])


### 16. Print the rank (number of dimensions) of a certain tensor.

In [48]:
tensor = torch.tensor([1,2,3])
print(tensor.ndimension())

tensor = torch.tensor([[1,2,3], [4,5,6]])
print(tensor.ndimension())

1
2


### 17. Print the number of elements (items) in a ceratin tensor 

In [50]:
tensor = torch.tensor([1,2,3])
print(tensor.numel())

tensor = torch.tensor([[1,2,3], [4,5,6]])
print(tensor.numel())

3
6


### 18.  Initailize a tensor of size (5,4,3,2) with values randomly selected from the normal distribution (mean=-2, std=3), then print its shape, rank, and number of elements. 

In [51]:
tensor = torch.empty((5,4,3,2)).normal_(-2, 3)
print(tensor.shape)
print(tensor.ndimension())
print(tensor.numel())

torch.Size([5, 4, 3, 2])
4
120


## D. Tensor Reshaping
### 1. Initialize a tensor with a range of values from 0 to 8, and reshape it to 3x3 matrix using 2 methods. 

#### view()
1. It returns a tensor with the new shape that will share the underlying data with the original tensor.
1. It can only operate on contiguous tensors. 
1. It is less flexible but it has a good performance

#### reshape()
1. It returns a copy of the original tensor. 
1. It can operate on both contiguous and non-contiguous tensors. 
1. It is more flexible but it has a performance loss.

In [1]:
import torch
print(torch.__version__)

1.9.0+cu102


In [2]:
tensor = torch.arange(9)
print(tensor)

reshaped_tensor = tensor.view(3,3)
print(reshaped_tensor)

reshaped_tensor = tensor.reshape(3,3)
print(reshaped_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


### 2. Transpose a matrix.

In [3]:
matrix = torch.rand((5,2))
transposed_tensor = matrix.t()
print(transposed_tensor)
print(transposed_tensor.shape)

tensor([[0.2592, 0.5358, 0.0560, 0.1593, 0.1549],
        [0.1719, 0.4957, 0.6905, 0.3803, 0.7402]])
torch.Size([2, 5])


### 3. Return the transposed tensor back to its shape using view()
1. The transposed tensor is not a continguous block of memory.

In [6]:
reshaped_matrix = transposed_tensor.contiguous().view(10)
print(reshaped_matrix)
print(reshaped_matrix.shape)

tensor([0.2592, 0.5358, 0.0560, 0.1593, 0.1549, 0.1719, 0.4957, 0.6905, 0.3803,
        0.7402])
torch.Size([10])


### 4. Initialize 2 tensors and concatenate them on vertically and horizontally respectively. 

In [9]:
first_tensor = torch.rand((5,2))
second_tensor = torch.randn((5,2))

vertical_concatenation = torch.cat((first_tensor, second_tensor), dim=0)
print(vertical_concatenation)
print(vertical_concatenation.shape)

horizontal_concatenation = torch.cat((first_tensor, second_tensor), dim=1)
print(horizontal_concatenation)
print(horizontal_concatenation.shape)

tensor([[ 0.7915,  0.9412],
        [ 0.9990,  0.6816],
        [ 0.0057,  0.4306],
        [ 0.5360,  0.4128],
        [ 0.8139,  0.1409],
        [ 1.8064, -0.0838],
        [ 0.8016, -2.6884],
        [-0.3070, -0.4440],
        [ 0.2758,  1.6708],
        [-0.2237, -1.2162]])
torch.Size([10, 2])
tensor([[ 0.7915,  0.9412,  1.8064, -0.0838],
        [ 0.9990,  0.6816,  0.8016, -2.6884],
        [ 0.0057,  0.4306, -0.3070, -0.4440],
        [ 0.5360,  0.4128,  0.2758,  1.6708],
        [ 0.8139,  0.1409, -0.2237, -1.2162]])
torch.Size([5, 4])


### 5. Unroll a tensor using 2 methods

In [15]:
tensor = torch.rand((5,2))

unrolled_tensor = tensor.view(-1)
print(unrolled_tensor)
print(unrolled_tensor.shape)

unrolled_tensor = tensor.reshape(-1)
print(unrolled_tensor)
print(unrolled_tensor.shape)

tensor([0.4417, 0.0862, 0.9252, 0.9104, 0.1938, 0.6863, 0.9178, 0.7788, 0.6879,
        0.3095])
torch.Size([10])
tensor([0.4417, 0.0862, 0.9252, 0.9104, 0.1938, 0.6863, 0.9178, 0.7788, 0.6879,
        0.3095])
torch.Size([10])


### 6. Unroll a batch using 2 methods 

In [16]:
batch_size = 64
batch = torch.rand((batch_size, 2, 5))

unrolled_batch = batch.view(batch_size, -1)
print(unrolled_batch.shape)

unrolled_batch = batch.reshape(batch_size, -1)
print(unrolled_batch.shape)

torch.Size([64, 10])
torch.Size([64, 10])


### 7. Swap the axes of a batch using 3 methods
1. transpose t() is a special case of permute()

In [21]:
batch_size = 64
batch = torch.rand((batch_size, 5, 2))

swapped_batch = batch.view(batch_size, 2, 5)
print(swapped_batch.shape)

swapped_batch = batch.reshape(batch_size, 2, 5)
print(swapped_batch.shape)

swapped_batch = batch.permute(0, 2, 1)
print(swapped_batch.shape)

torch.Size([64, 2, 5])
torch.Size([64, 2, 5])
torch.Size([64, 2, 5])


### 8. For a vector (rank-1 tensor), change it to rank-2 tensor using 2 methods.
1. [10] -> [1, 10]
1. [10] -> [10, 1]

In [23]:
rank_1_tensor = torch.rand(10)

rank_2_tensor = rank_1_tensor.reshape(1, -1)
print(rank_2_tensor.shape)

rank_2_tensor = rank_1_tensor.unsqueeze(0)
print(rank_2_tensor.shape)

torch.Size([1, 10])
torch.Size([1, 10])


In [24]:
rank_1_tensor = torch.rand(10)

rank_2_tensor = rank_1_tensor.reshape(-1, 1)
print(rank_2_tensor.shape)

rank_2_tensor = rank_1_tensor.unsqueeze(1)
print(rank_2_tensor.shape)

torch.Size([10, 1])
torch.Size([10, 1])


### 9. Change rank-1 tensor to rank-3, then change it to rank-2.
1. [10] -> [1, 1, 10] -> [1, 10]

In [28]:
rank_1_tensor = torch.arange(10)

rank_3_tensor = rank_1_tensor.unsqueeze(0).unsqueeze(1)
print(rank_3_tensor.shape)

rank_2_tensor = rank_3_tensor.squeeze(0)
print(rank_2_tensor.shape)

torch.Size([1, 1, 10])
torch.Size([1, 10])
