## Construct a tensor of rank 3 (cube) with the following dimension:
1. Number os rows = 3
1. Number of columns = 4
1. Depth size = 2

In [30]:
import torch

tensor_with_random_values = torch.randn(2, 3, 4)
print(tensor_with_random_values)

tensor([[[-0.0787, -2.8614, -1.1221, -0.3720],
         [-1.2420,  0.0831,  0.2329,  0.3559],
         [ 0.2777,  0.9143, -0.4208, -0.6168]],

        [[ 1.9731, -1.4547,  0.1618,  1.4317],
         [-0.1666, -0.3952,  0.0651,  0.3995],
         [-1.0912, -0.5120,  0.1655, -0.2120]]])


## Construct a tensor of rank 4 (vector of cubes) with the following dimension:
1. Number os rows = 4
1. Number of columns = 5
1. Depth size = 3
1. vector size = 2

In [31]:
import torch

tensor_with_random_values = torch.randn(2, 3, 4, 5)
print(tensor_with_random_values)

tensor([[[[-0.9182,  0.8968,  0.8650,  0.3794, -0.2428],
          [-0.1181,  1.1542,  1.1069, -1.7583,  0.2619],
          [ 1.0271, -1.0482,  1.0546,  0.0674,  1.5709],
          [ 0.4295, -0.6994,  0.6789, -0.0984, -0.2225]],

         [[ 1.0747, -0.2917,  0.8106,  0.1456, -0.0046],
          [ 1.2284, -1.0525,  0.3537, -0.5194,  1.6411],
          [ 0.0686,  1.4003, -0.4113, -2.3932,  0.2568],
          [-0.1985, -1.2003, -4.1310,  0.6323,  1.3276]],

         [[-0.0054, -0.1173, -0.8095,  0.6822,  0.7789],
          [-1.2235,  1.9960, -1.3337, -0.4627, -1.1197],
          [-2.5956, -0.3056, -0.2668,  0.6200, -1.8841],
          [-0.1638,  0.8309, -1.2452, -0.3574,  0.3953]]],


        [[[ 1.2685,  0.2537,  0.1424,  1.1698, -0.7100],
          [ 0.0847, -0.7181, -0.8719, -1.0052,  0.9191],
          [ 0.4787,  0.6717,  1.4439, -1.5378, -0.7973],
          [-0.8372,  1.4587,  0.0432,  0.1837, -0.6475]],

         [[ 0.1866,  1.4688, -0.1613,  1.5025, -1.4038],
          [ 0.6593,  

## Construct a tensor of rank 4 (vector of cubes) with the following dimension:
1. Number os rows = 4
1. Number of columns = 5
1. Depth size = 2
1. vector size = 3

In [1]:
import torch

tensor_with_random_values = torch.randn(3, 2, 4, 5)
print(tensor_with_random_values)

tensor([[[[ 0.3140, -0.4612,  0.8004, -0.3850,  0.5290],
          [ 1.8450, -0.0470, -1.5352,  1.1106, -0.3840],
          [ 0.0987, -1.2207,  0.3232,  1.1271,  0.2307],
          [ 0.4603, -0.6091, -1.0030, -0.5472,  0.6645]],

         [[-0.1747, -1.0136,  0.1579, -0.6610,  0.6646],
          [ 1.7805, -0.2957, -1.4201,  0.0955, -0.6500],
          [-1.5607,  0.9535,  2.0689, -1.2082, -0.5277],
          [ 1.2329,  1.6441, -1.0598,  1.8783,  0.6704]]],


        [[[ 0.1255,  2.4196, -1.7391, -0.1621, -0.2275],
          [-1.1628,  0.5307,  2.4563, -0.4337,  0.0850],
          [-0.8884, -0.8784,  0.8913,  0.1684, -0.2539],
          [ 0.8569,  0.8522, -0.3774, -0.5121,  0.9697]],

         [[ 0.7236, -0.1180, -0.6905, -1.0999,  1.4857],
          [-1.6678,  0.7434, -0.4795, -1.4634, -0.0660],
          [-0.1250, -0.0216, -0.3125,  0.9142, -0.1299],
          [ 0.9610,  0.3582,  0.1631,  1.9695,  0.6060]]],


        [[[-1.7126, -0.5719,  1.4306, -1.3214,  1.6483],
          [ 0.6085,

## Perform the following steps:

1. Construct a tensor of rank 2 (matrix) with the following dimension:
    1. Number os rows = 2
    1. Number of columns = 3

1. Apply Softmax on each column and row, respectively.

In [8]:
import torch 

def sum_over_softmax_values(arr, dim):
    print(f'dim = {dim}')
    
    softmax = torch.softmax(arr, dim = dim)
    print(softmax)
    print(softmax.shape)
    
    summation = torch.sum(softmax, dim = dim)
    print(summation)
    print(summation.shape)

tensor_with_random_values = torch.randn(2, 3)
print(tensor_with_random_values)    
print(tensor_with_random_values.shape)    

print()
print()
print()

sum_over_softmax_values(tensor_with_random_values, 0) 
sum_over_softmax_values(tensor_with_random_values, -2)

print()
print()
print()

sum_over_softmax_values(tensor_with_random_values, 1)  
sum_over_softmax_values(tensor_with_random_values, -1) 

tensor([[-0.2385,  1.3169,  0.7576],
        [ 0.4305, -0.8078, -1.4185]])
torch.Size([2, 3])



dim = 0
tensor([[0.3387, 0.8933, 0.8981],
        [0.6613, 0.1067, 0.1019]])
torch.Size([2, 3])
tensor([1.0000, 1.0000, 1.0000])
torch.Size([3])
dim = -2
tensor([[0.3387, 0.8933, 0.8981],
        [0.6613, 0.1067, 0.1019]])
torch.Size([2, 3])
tensor([1.0000, 1.0000, 1.0000])
torch.Size([3])



dim = 1
tensor([[0.1184, 0.5610, 0.3206],
        [0.6910, 0.2003, 0.1088]])
torch.Size([2, 3])
tensor([1.0000, 1.0000])
torch.Size([2])
dim = -1
tensor([[0.1184, 0.5610, 0.3206],
        [0.6910, 0.2003, 0.1088]])
torch.Size([2, 3])
tensor([1.0000, 1.0000])
torch.Size([2])


## Perform the following steps:

1. Construct a tensor of rank 3 (cube) with the following dimension:
    1. Number os rows = 9
    1. Number of columns = 12
    1. Depth size = 6

1. Apply Softmax on each (row, column), (depth, column), and (depth, row), respectively.

In [13]:
import torch 

def sum_over_softmax_values(arr, dim):
    print(f'dim = {dim}')
    
    softmax = torch.softmax(arr, dim = dim)
    print(softmax.shape)
    
    summation = torch.sum(softmax, dim = dim)
    print(summation)
    print(summation.shape)
    
tensor_with_random_values = torch.randn(6, 9, 12)
print(tensor_with_random_values.shape)    
print()

sum_over_softmax_values(tensor_with_random_values, -3) 
sum_over_softmax_values(tensor_with_random_values, 0)

print()
print()
print()

sum_over_softmax_values(tensor_with_random_values, -2)    
sum_over_softmax_values(tensor_with_random_values, 1)

print()
print()
print()

sum_over_softmax_values(tensor_with_random_values, -1)      
sum_over_softmax_values(tensor_with_random_values, 2)    

torch.Size([6, 9, 12])

dim = -3
torch.Size([6, 9, 12])
tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
         1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000,

## References
1. https://sparrow.dev/pytorch-softmax/
1. https://pytorch.org/docs/stable/generated/torch.nn.Softmax.html 